from __future__ import annotations

from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[2]
PROJECT_SUMMARY_CSV = ROOT / "results" / "rq1" / "project_summary.csv"
OVERALL_SUMMARY_CSV = ROOT / "results" / "rq1" / "overall_summary.csv"
OUTPUT_TEX = ROOT / "paper" / "generated_tables" / "rq1_full_metrics_table.tex"

PROJECT_LABELS = {
    "Orange_OpenSourceouds_android_wf108176393": "ouds-android",
    "bmad simbmad ecosystem_wf69576399": "bmad",
    "ccpay_wf6192976": "ccpay",
    "collinbarrettFilterLists_wf75763098": "FilterLists",
    "daos_wf9020028": "daos",
    "jod-yksilo-ui_wf83806327": "jod-yksilo-ui",
    "m2Gilesm2os_wf105026558": "m2os",
    "pr3y_Bruce_wf121541665": "Bruce",
    "radareorg_radare2_wf1989843": "radare2",
    "rustlang_wf51073": "rust",
}

PROJECT_ORDER = [
    "ouds-android",
    "bmad",
    "ccpay",
    "FilterLists",
    "daos",
    "jod-yksilo-ui",
    "m2os",
    "Bruce",
    "radare2",
    "rust",
]

PREFERRED_MODEL_ORDER = ["Baseline", "DT", "KNN", "LR", "RF", "SGB", "SVR", "XGB", "HGB", "LSTM"]

LOWER_IS_BETTER = {"rmse", "mae", "nrmse"}
HIGHER_IS_BETTER = {"r2"}


def format_metric(metric: str, value: float) -> str:
    if metric in {"rmse", "mae"}:
        return f"{value:.0f}"
    return f"{value:.3f}"


def choose_best(metric: str, values: dict[str, float]) -> set[str]:
    if metric in LOWER_IS_BETTER:
        best = min(values.values())
    else:
        best = max(values.values())
    return {model for model, value in values.items() if abs(value - best) < 1e-12}


def make_table() -> str:
    project_df = pd.read_csv(PROJECT_SUMMARY_CSV)
    overall_df = pd.read_csv(OVERALL_SUMMARY_CSV)
    model_order = [model for model in PREFERRED_MODEL_ORDER if model in project_df["model"].unique()]

    project_df["project_label"] = project_df["project"].map(PROJECT_LABELS)
    order_map = {name: idx for idx, name in enumerate(PROJECT_ORDER)}
    model_order_map = {name: idx for idx, name in enumerate(model_order)}
    project_df = project_df.sort_values(
        ["project_label", "model"],
        key=lambda s: s.map(
            lambda value: order_map.get(value, 999)
            if value in order_map
            else model_order_map.get(value, 999)
        ),
    )

    lines = [
        "% Auto-generated by scripts/generate_rq1_full_table_tex.py",
        "\\begin{table*}[!tbp]",
        "\\centering",
        "\\scriptsize",
        "\\renewcommand{\\arraystretch}{1.1}",
        "\\setlength{\\tabcolsep}{2.5pt}",
        "\\caption{Prediction results by project. Lower is better except for $R^2$; bold marks the best model in each project-metric row.}",
        "\\label{tab:rq1-rmse}",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tabular}{ll" + ("c" * len(model_order)) + "}",
        "\\toprule",
        "\\textbf{Project} & \\textbf{Metric} &",
        " & ".join(f"\\textbf{{{model}}}" for model in model_order) + r" \\",
        "\\midrule",
    ]

    metric_rows = [
        ("RMSE", "rmse"),
        ("MAE", "mae"),
        ("$R^2$", "r2"),
        ("NRMSE", "nrmse"),
    ]

    for idx, project in enumerate(PROJECT_ORDER):
        proj = project_df.loc[project_df["project_label"] == project].copy()
        proj = proj.set_index("model")
        for row_idx, (metric_label, metric_key) in enumerate(metric_rows):
            values = {model: float(proj.loc[model, metric_key]) for model in model_order}
            prefix = rf"\multirow{{4}}{{*}}{{{project}}}" if row_idx == 0 else " "
            lines.append(
                prefix
                + " & "
                + metric_label
                + " & "
                + " & ".join(
                    f"\\textbf{{{format_metric(metric_key, values[model])}}}"
                    if model in choose_best(metric_key, values)
                    else format_metric(metric_key, values[model])
                    for model in model_order
                )
                + r" \\"
            )
        if idx != len(PROJECT_ORDER) - 1:
            lines.append("\\midrule")

    lines.append("\\midrule")

    overall = overall_df.set_index("model")
    for row_idx, (metric_label, metric_key) in enumerate(metric_rows):
        values = {model: float(overall.loc[model, metric_key]) for model in model_order}
        prefix = r"\multirow{4}{*}{\textbf{Global Avg}}" if row_idx == 0 else " "
        lines.append(
            prefix
            + " & "
            + metric_label
            + " & "
            + " & ".join(
                f"\\textbf{{{format_metric(metric_key, values[model])}}}"
                if model in choose_best(metric_key, values)
                else format_metric(metric_key, values[model])
                for model in model_order
            )
            + r" \\"
        )

    lines.extend(["\\bottomrule", "\\end{tabular}", "}", "\\end{table*}"])
    return "\n".join(lines)


def main() -> None:
    OUTPUT_TEX.write_text(make_table(), encoding="utf-8")
    print(f"Saved {OUTPUT_TEX}")


if __name__ == "__main__":
    main()
