from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

SHARED_DIR = Path(__file__).resolve().parents[1] / "shared"
if str(SHARED_DIR) not in sys.path:
    sys.path.insert(0, str(SHARED_DIR))

from rq2_feature_metadata import FAMILY_LITERATURE_RATIONALE, infer_feature_group


ROOT = Path(__file__).resolve().parents[2]
INPUT_CSV = ROOT / "results" / "rq1" / "global_kept_features.csv"
OUTPUT_TEX = ROOT / "paper" / "generated_tables" / "feature_summary_retained.tex"

FAMILY_ORDER = [
    "Temporal persistence",
    "Developer and repository context",
    "Workflow context",
    "Change activity and review context",
    "Workflow YAML structure",
    "Curated microservice file groups",
    "Commit timeline structure",
    "Patch change shape",
    "Patch workflow semantics",
    "Patch build and dependency semantics",
    "Patch deployment semantics",
    "Patch microservice and configuration semantics",
    "Patch test semantics",
    "Other",
]


def latex_escape(value: object) -> str:
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "_": r"\_",
        "%": r"\%",
        "&": r"\&",
        "#": r"\#",
        "{": r"\{",
        "}": r"\}",
    }
    for src, dst in replacements.items():
        text = text.replace(src, dst)
    return text


def format_examples(features: list[str], limit: int = 4) -> str:
    examples = features[:limit]
    return ", ".join(r"\texttt{" + latex_escape(feature) + "}" for feature in examples)


def main() -> None:
    kept = pd.read_csv(INPUT_CSV)
    if "feature" not in kept.columns:
        raise ValueError(f"Missing 'feature' column in {INPUT_CSV}")

    kept["family"] = kept["feature"].map(infer_feature_group)

    grouped = (
        kept.groupby("family", as_index=False)
        .agg(
            retained_count=("feature", "count"),
            features=("feature", lambda values: sorted(values)),
        )
        .copy()
    )
    order_map = {family: index for index, family in enumerate(FAMILY_ORDER)}
    grouped["order"] = grouped["family"].map(lambda family: order_map.get(family, len(FAMILY_ORDER)))
    grouped = grouped.sort_values(["order", "family"]).reset_index(drop=True)

    lines = [
        "% Auto-generated by scripts/generate_feature_summary_retained_tex.py",
        r"\begin{table*}[!tbp]",
        r"\centering",
        r"\scriptsize",
        r"\renewcommand{\arraystretch}{1.12}",
        r"\setlength{\tabcolsep}{4pt}",
        r"\caption{Retained predictor groups after the final global screening step.}",
        r"\label{tab:feature_summary_grouped}",
        r"\begin{tabular}{p{3.2cm}cp{4.8cm}p{7.0cm}}",
        r"\toprule",
        r"\textbf{Feature family} & \textbf{Count} & \textbf{Representative retained predictors} & \textbf{Literature inspiration} \\",
        r"\midrule",
    ]

    for _, row in grouped.iterrows():
        lines.append(
            " & ".join(
                [
                    latex_escape(row["family"]),
                    str(int(row["retained_count"])),
                    format_examples(row["features"]),
                    latex_escape(FAMILY_LITERATURE_RATIONALE.get(row["family"], "General workflow-duration modeling context.")),
                ]
            )
            + r" \\"
        )

    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table*}",
            "",
        ]
    )

    OUTPUT_TEX.write_text("\n".join(lines), encoding="utf-8")
    print(f"[Feature-Summary] Wrote {OUTPUT_TEX}")


if __name__ == "__main__":
    main()
